const pool = require('./db');

async function dropTableConstraint() {
  const client = await pool.connect();
  try {
    console.log('Dropping table_id constraint from orders to allow merging tables...');
    // Drop the constraint if it exists (the name generated by postgres is typically orders_table_id_fkey)
    await client.query(`ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_table_id_fkey;`);
    
    // Also ensure the column can fit a long string of IDs if needed
    await client.query(`ALTER TABLE orders ALTER COLUMN table_id TYPE VARCHAR(255);`);
    
    console.log('Successfully updated orders schema for table merging.');
  } catch (err) {
    console.error('Error modifying schema:', err);
  } finally {
    client.release();
    process.exit(0);
  }
}

dropTableConstraint();
